from presentacion.menu import menu_principal
from negocio.negocio_producto import lista_producto
from presentacion.presentacion_producto import solicitar_datos_producto

solicitar_datos_producto()
lista_producto()